export const FETCH_PRICE = 'FETCH_PRICE';
export const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS';

export const REQUEST_ERRORED = 'REQUEST_ERRORED';

export const UPDATE_PRICE = 'UPDATE_PRICE';

export const FETCH_GRAPH = 'FETCH_GRAPH';
export const FETCH_GRAPH_SUCCESS = 'FETCH_GRAPH';
